name: python bbDoChk.py
# Node.js 16 ➜ Node.js 20

on:
  schedule:
    # - cron: '0 0 * * 1' # At 00:00 on Monday
    # kazdych 15 minut spustit https://crontab.guru/#15_*_*_*_*
    - cron: "*/16 * * * *"

jobs:
  build:
    # runs-on: ubuntu-22.04
    # runs-on: ubuntu-24.04
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v5
        with:
          # python-version: "3.10" # install the python version needed
          python-version: "3.11" # install the python version needed
          # python-version: "3.12" # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # zzzzzzzzzzzzzzzz
      - name: sudo apt-get update
        run: |
          sudo apt-get update && sudo apt-get install -y \
          libwoff2dec1 \
          libvpx7 \
          libevent-2.1-7 \
          libopus0 \
          libgstallocators-1.0-0 \
          libgstapp-1.0-0 \
          libgstpbutils-1.0-0 \
          libgstaudio-1.0-0 \
          libgstgl-1.0-0 \
          libgsttag-1.0-0 \
          libgstvideo-1.0-0 \
          libgstcodecparsers-1.0-0 \
          libgstfft-1.0-0 \
          libflite1 \
          libflite_usenglish1 \
          libflite_cmu_grapheme_lang1 \
          libflite_cmu_grapheme_lex1 \
          libflite_cmu_indic_lang1 \
          libflite_cmu_indic_lex1 \
          libflite_cmulex1 \
          libflite_cmu_time_awb1 \
          libflite_cmu_us_awb1 \
          libflite_cmu_us_kal16 \
          libflite_cmu_us_kal1 \
          libflite_cmu_us_rms1 \
          libflite_cmu_us_slt1 \
          libavif13 \
          libharfbuzz-icu0 \
          libhyphen0 \
          libmanette-0.2-0 \
          libgles2 \
          libx264-160
      # zzzzzzzzzzzzzzzz
      - name: playwright install
        run: |
          playwright install

      - name: execute py script # run main.py
        env:
          SOME_SECRET: ${{ secrets.SOME_SECRET }}
        run: python bbDoChk.py >> DoChk.Log

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "ppBB bot update" --allow-empty)

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
